name: Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Release branch (needed for major and minor releases)
        required: true
      version:
        description: Release version
        required: true
      dry-run:
        description: Set the dry run if testing the changes to release process. Nothing will be published.
        required: true

concurrency: rel-${{ github.ref }}

defaults:
  run:
    shell: bash

jobs:

  show-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Version: ${{ inputs.version }}  " >> $GITHUB_STEP_SUMMARY
          echo "Release branch: ${{ inputs.branch }}  " >> $GITHUB_STEP_SUMMARY
          echo "Workflow branch: ${{ github.ref_name }}  " >> $GITHUB_STEP_SUMMARY
          echo "Dry run: ${{ inputs.dry-run }}  " >> $GITHUB_STEP_SUMMARY

  env:
    uses: ./.github/workflows/x-env.yml

  create-tags:
    name: Create tags
    needs: [env]
    uses: ./.github/workflows/x-create-tags.yml
    with:
      gh-org: ${{ needs.env.outputs.gh-org }}
      tag: ${{ github.event.inputs.version }}
      branch: ${{ github.event.inputs.branch }}
      set-versions: true
      dry-run: ${{ needs.env.outputs.dry-run }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  create-gh-releases:
    name: Create Github releases
    needs: [env, create-tags]
    uses: ./.github/workflows/x-create-gh-releases.yml
    with:
      gh-org: ${{ needs.env.outputs.gh-org }}
      tag: ${{ github.event.inputs.version }}
      prerelease: false
      dry-run: ${{ needs.env.outputs.dry-run }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  keycloak-client:
    name: Keycloak Client
    needs: [env, create-tags, create-gh-releases]
    uses: ./.github/workflows/x-keycloak-client.yml
    with:
      gh-org: ${{ needs.env.outputs.gh-org }}
      mvn-url: ${{ needs.env.outputs.mvn-releases-url }}
      version: ${{ github.event.inputs.version }}
      tag: ${{ github.event.inputs.version }}
      dry-run: ${{ needs.env.outputs.dry-run }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      MVN_USERNAME: ${{ secrets.MVN_USERNAME }}
      MVN_TOKEN: ${{ secrets.MVN_TOKEN }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

  publish-gh-releases:
    name: Publish releases
    needs: [env, keycloak-client]
    uses: ./.github/workflows/x-publish-gh-releases.yml
    with:
      gh-org: ${{ needs.env.outputs.gh-org }}
      tag: ${{ github.event.inputs.version }}
      dry-run: ${{ needs.env.outputs.dry-run }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

